/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wind_ndk_videoplayer_VideoPlayer */

#ifndef _Included_com_wind_ndk_videoplayer_VideoPlayer
#define _Included_com_wind_ndk_videoplayer_VideoPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wind_ndk_videoplayer_VideoPlayer
 * Method:    nativePrepare
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_videoplayer_VideoPlayer_nativePrepare
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wind_ndk_videoplayer_VideoPlayer
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wind_ndk_videoplayer_VideoPlayer_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wind_ndk_videoplayer_VideoPlayer
 * Method:    nativeSetDataSource
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_videoplayer_VideoPlayer_nativeSetDataSource
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_wind_ndk_videoplayer_VideoPlayer
 * Method:    nativePlay
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_videoplayer_VideoPlayer_nativePlay
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wind_ndk_videoplayer_VideoPlayer
 * Method:    nativeSurfaceCreated
 * Signature: (JLandroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_videoplayer_VideoPlayer_nativeSurfaceCreated
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_wind_ndk_videoplayer_VideoPlayer
 * Method:    nativeSurfaceChanged
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_videoplayer_VideoPlayer_nativeSurfaceChanged
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_wind_ndk_videoplayer_VideoPlayer
 * Method:    nativeSurfaceDestroyed
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_videoplayer_VideoPlayer_nativeSurfaceDestroyed
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
